"""Generate ``docs/registers.md`` from :mod:`fujilib.registry` (design §5.1).

The register reference is generated, never edited by hand, so it cannot drift
from the map the library uses. It is the page that gets reviewed against the
manual. CI re-runs this with ``--check`` and fails if the committed page is
stale.

Usage:
    python scripts/gen_register_docs.py            # regenerate (writes the page)
    python scripts/gen_register_docs.py --check    # exit 1 if the page is stale
"""

from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path
from typing import TYPE_CHECKING

from fujilib.protocol.modbus.codec import DataType
from fujilib.registry.regions import Evidence, RegisterTable
from fujilib.registry.registers import REGISTRY, LogSpec, RegisterSpec, ScalingKind
from fujilib.registry.write_policy import KEY_SIMULATION_ADDRESS, OPERATIONS, WRITE_ENVELOPE

if TYPE_CHECKING:
    from collections.abc import Iterable, Sequence
    from enum import IntEnum

    from fujilib.devices.capability import Capability

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT = REPO_ROOT / "docs" / "registers.md"

_FC_NAMES = {0x03: "read holding", 0x04: "read input", 0x06: "write single", 0x10: "write multiple"}

_HEADER = """\
---
description: The Fuji ZP-series MODBUS register map as fujilib models it.
---

# Register map

<!-- Generated by scripts/gen_register_docs.py from fujilib.registry. Do not edit. -->

This page is generated from `fujilib.registry` (design §5.1). To change it, change the
registry and run `python scripts/gen_register_docs.py`.

## Conventions

- **Address** is the 0-based relative address, exactly as on the wire. **Register** is
  the register number: 40001 + address for holding registers, 30001 + address for input
  registers.
- **FC** lists the function codes fujilib may use: 03 read holding, 04 read input,
  06 write single, 10 write multiple. FC06 reaches only 0000h-009Dh.
- **Tier** is the safety tier of a write. Every read is `READ_ONLY`, and so is every
  register fujilib never writes.
- **What is writable.** Only the reviewed subset of design §5.4: the calibration gases
  and calibration scope, the response times, output hold and the hold settings, and each
  channel's range and range method. They are documented, the bench unit does not
  contradict them, they are not options, and the bench analyzer can test them all.
  Every other register is read-only, including the documented alarm, schedule, key-lock,
  averaging, O2-correction, peak-alarm, blowback, measurement-point and reference-gas
  settings.
- **Limits** are raw, before scaling. For a writable register they are the limits of a
  write: the narrower of the two manuals' where they disagree, since the MODBUS manual
  defers setting ranges to the instruction manual (TN5A1190a p.28). `write` lists the
  only values a write may use, or its limits in percent of the range's full scale.
  **Scaling** says where the decimal point comes from:
  `inline` (the two registers after a concentration), `by_range` (the channel and range's
  decimal-point register), `by_alarm_target` (the range of the alarm's target channel),
  or `fixed(n)`. A scaled concentration takes its unit from the same place.
- **Evidence**: `documented` by the manuals; `observed` on the bench unit (firmware 1.02)
  but undocumented; `inferred`, an interpretation; `contested`, documented but
  contradicted by the bench unit. Only documented registers are ever writable.
- **Ref** gives the PDF page of the manual, which matches the page markers of the text
  extracts. The printed page number is 3 lower in TN5A1190a, 13 lower in TN2ZPAb and 8
  lower in TN5A1191b.
"""


def _cell(text: object) -> str:
    return str(text).replace("|", "\\|")


def _row(cells: Iterable[object]) -> str:
    return "| " + " | ".join(_cell(c) for c in cells) + " |\n"


def _table(headers: Sequence[str], rows: Iterable[Sequence[object]]) -> str:
    out = [_row(headers), "|" + "---|" * len(headers) + "\n"]
    out.extend(_row(r) for r in rows)
    return "".join(out)


def _hex(address: int) -> str:
    return f"{address:04X}h"


def _span(spec: RegisterSpec) -> str:
    if spec.count == 1:
        return _hex(spec.address)
    return f"{_hex(spec.address)}-{_hex(spec.last_address)}"


def _type(spec: RegisterSpec) -> str:
    if spec.enum is not None:
        return spec.enum.__name__
    if spec.dtype is DataType.CHAR:
        return f"char[{spec.count}]"
    return spec.dtype.value


def _functions(fcs: frozenset[int]) -> str:
    return " ".join(f"{fc:02X}" for fc in sorted(fcs))


def _limits(spec: RegisterSpec) -> str:
    parts: list[str] = []
    if spec.minimum is not None or spec.maximum is not None:
        low = "" if spec.minimum is None else spec.minimum
        high = "" if spec.maximum is None else spec.maximum
        parts.append(f"{low}..{high}")
    if spec.write_values is not None:
        parts.append("write " + ", ".join(str(v) for v in sorted(spec.write_values)))
    if spec.write_percent_fs is not None:
        low_fs, high_fs = spec.write_percent_fs
        parts.append(f"write {low_fs}..{high_fs} %FS")
    return "; ".join(parts) or "-"


def _scaling(spec: RegisterSpec) -> str:
    parts = [] if spec.scaling.kind is ScalingKind.NONE else [str(spec.scaling)]
    if spec.unit:
        parts.append(spec.unit)
    return ", ".join(parts) or "-"


def _requires(capability: Capability) -> str:
    return " ".join(m.name or "" for m in capability) if capability else "-"


def _register_group(specs: Sequence[RegisterSpec]) -> str:
    rows = [
        (
            _span(s),
            s.register_number,
            f"`{s.name}`",
            _type(s),
            _functions(s.read_functions | s.write_functions),
            s.safety.name,
            _limits(s),
            _scaling(s),
            _requires(s.requires),
            s.evidence.value,
            s.manual_ref,
            s.doc,
        )
        for s in specs
    ]
    headers = (
        "Address",
        "Register",
        "Name",
        "Type",
        "FC",
        "Tier",
        "Limits",
        "Scaling",
        "Requires",
        "Evidence",
        "Ref",
        "Description",
    )
    out = [_table(headers, rows)]
    notes: dict[str, list[str]] = {}
    for s in specs:
        if s.notes:
            notes.setdefault(s.notes, []).append(s.name)
    if notes:
        out.append("\n")
        for note, names in notes.items():
            out.append(f"- {', '.join(f'`{n}`' for n in names)}: {note}\n")
    return "".join(out)


def _registers(table: RegisterTable) -> str:
    specs = REGISTRY.in_table(table)
    out: list[str] = []
    groups = dict.fromkeys(s.group for s in specs)
    for group in groups:
        members = [s for s in specs if s.group == group]
        out.append(f"\n### {group}\n\n")
        out.append(_register_group(members))
    return "".join(out)


def _log(log: LogSpec) -> str:
    out = [f"\n### {log.group}\n\n", f"{log.doc}\n\n"]
    layout = (
        f"`{log.name}`: FC04, {log.channels} region(s) of {log.records} records x "
        f"{log.record_words} words from {_hex(log.base)} to {_hex(log.last_address)}"
    )
    if log.channels > 1:
        layout += f"; channel c starts at {_hex(log.base)} + {log.channel_stride}(c - 1)"
    layout += (
        f". Requires: {_requires(log.requires)}. Evidence: {log.evidence.value}. "
        f"Ref: {log.manual_ref}.\n\n"
    )
    out.append(layout)
    rows = [
        (
            f"+{f.offset}" if f.count == 1 else f"+{f.offset}..+{f.offset + f.count - 1}",
            f"`{f.name}`",
            f.enum.__name__ if f.enum is not None else f.dtype.value,
            "-" if f.scaling.kind is ScalingKind.NONE else str(f.scaling),
            f.doc,
        )
        for f in log.fields
    ]
    out.append(_table(("Offset", "Field", "Type", "Scaling", "Description"), rows))
    if log.notes:
        out.append(f"\n{log.notes}\n")
    return "".join(out)


def _enums() -> str:
    seen: dict[str, type[IntEnum]] = {}
    for spec in REGISTRY:
        if spec.enum is not None:
            seen.setdefault(spec.enum.__name__, spec.enum)
    for log in REGISTRY.logs:
        for fld in log.fields:
            if fld.enum is not None:
                seen.setdefault(fld.enum.__name__, fld.enum)
    out: list[str] = []
    for name in sorted(seen):
        members = ", ".join(f"{int(m)} `{m.name}`" for m in seen[name])
        out.append(f"- **{name}**: {members}\n")
    return "".join(out)


def _summary() -> str:
    rows = []
    for table in RegisterTable:
        specs = REGISTRY.in_table(table)
        by_evidence = {e: sum(1 for s in specs if s.evidence is e) for e in Evidence}
        rows.append(
            (
                table.value,
                len(specs),
                sum(1 for s in specs if s.writable),
                *(by_evidence[e] for e in Evidence),
            )
        )
    headers = ("Table", "Registers", "Writable", *(e.value.capitalize() for e in Evidence))
    return _table(headers, rows)


def _envelope() -> str:
    out = [
        "Everything fujilib may ever write. The envelope is frozen and independent of the "
        "registry; the Modbus client re-checks every write against it (design §5.4). "
        f"{_hex(KEY_SIMULATION_ADDRESS)} (key simulation) and 00A4h-00ABh are outside it.\n\n",
        _table(
            ("FC", "From", "To"),
            (
                (f"{r.fc:02X} ({_FC_NAMES[r.fc]})", _hex(r.first), _hex(r.last))
                for r in WRITE_ENVELOPE
            ),
        ),
        "\n### Operation commands\n\n",
        "Written with FC06, one value each; not reachable by writing a parameter.\n\n",
        _table(
            ("Address", "Register", "Operation", "Value", "Tier", "Requires", "Ref", "Effect"),
            (
                (
                    _hex(op.address),
                    op.register_number,
                    f"`{op.name}`",
                    op.value,
                    op.safety.name,
                    _requires(op.requires),
                    op.manual_ref,
                    op.effect,
                )
                for op in OPERATIONS.values()
            ),
        ),
    ]
    return "".join(out)


def render() -> str:
    """Render the whole page."""
    parts = [
        _HEADER,
        "\n## Summary\n\n",
        _summary(),
        "\n## Holding registers\n",
        _registers(RegisterTable.HOLDING),
        "\n## Input registers\n",
        _registers(RegisterTable.INPUT),
        "\n## Logs\n",
        *(_log(log) for log in REGISTRY.logs),
        "\n## Write envelope\n\n",
        _envelope(),
        "\n## Enumerations\n\n",
        _enums(),
    ]
    return "".join(parts).rstrip() + "\n"


def main(argv: Sequence[str] | None = None) -> int:
    """Regenerate the page, or with ``--check`` report whether it is stale."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit with status 1 if the committed page is stale.",
    )
    args = parser.parse_args(argv)
    rendered = render()
    if args.check:
        existing = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if existing != rendered:
            diff = "".join(
                difflib.unified_diff(
                    existing.splitlines(keepends=True),
                    rendered.splitlines(keepends=True),
                    fromfile=str(OUTPUT.relative_to(REPO_ROOT)),
                    tofile="<regenerated>",
                )
            )
            sys.stderr.write(
                f"{OUTPUT.relative_to(REPO_ROOT)} is stale. "
                "Run `python scripts/gen_register_docs.py` to regenerate.\n"
            )
            sys.stderr.write(diff)
            return 1
        return 0
    OUTPUT.write_text(rendered, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
